### PR TITLE
Add minimize functionality, change maximize behavior, fix view bug

### PR DESCRIPTION
**Pull request by MilWolf**
-Add minimize functionality
	->minimize only works when the DockNode is floating
	->minimize calls iconify function

-Fix a bug causing the docknode to disappear (Linux Mint 64 bits, java 8 Oracle)
	->appears when the user drag a docknode outside, then maximize the floating node and maximize again the floating node

-Change maximize behavior
        ->maximize the first time (unchanged)
        ->maximize the second time : resize stage to the size before the first maximization

### CODE REVIEW

**Comment by hkmoon** [comment]
Hi @MilWolf 

Thank you for the PR! You implementation is great help for having minimize function of floating nodes! I haven't testes it in Windows. In MacOSX, it looks fine.

There is one thing I would like to point out. You have changed the public functions in DockPane which could lead to the failure of backward compatibility. In such a case, you can just extend the functions by using function overriding because we make sure other users might use e.g. ```loadCollection(String path)```. When you change the function signature with ```loadCollection(File file)```, some users codes referring this function will have problems in compile time. When you extend functionality, I recommend not to try to change it, just extend it.

Cheers,
HongKee

**Comment by MilWolf** [comment]
Hello HongKee Moon,

I misused github pull request functionality because i'm not used to use it
:-D
I only wanted to add minimize functionality and view bug correction but i
didn't want to push modififications relative to the layout storage.
So i made a new pull request with the first commit only.

I understand the problems relative to backward compatibility and this was
not my intention to break it.

Also i have a question about the implementation of the preferences
storage/load.
The DockNode could be closed after storage, if we load the saved
preferences, an error occured because the DockNode cannot be retrieved. Is
that the wanted behavior ?
Anyway i'm working on this, the changes on loadCollection was an extract of
my attemps to handle this.

Are you using this library at work ?

Cheers,

MilWolf.

2016-10-20 11:19 GMT+02:00 HongKee Moon <notifications@github.com>:

**Comment by hkmoon** [comment]
Hi @MilWolf 

> I only wanted to add minimize functionality and view bug correction but i didn't want to push modififications relative to the layout storage. So i made a new pull request with the first commit only.
> I understand the problems relative to backward compatibility and this was not my intention to break it.

Thanks, you can try to get the final stage together step by step. ;)


> Also i have a question about the implementation of the preferences storage/load. The DockNode could be closed after storage, if we load the saved preferences, an error occured because the DockNode cannot be retrieved. Is that the wanted behavior ? Anyway i'm working on this, the changes on loadCollection was an extract of my attemps to handle this.

Sorry that I did not provide any good example codes for using preference store/restore. Here is a snippet of how I am currently using in main.

```java
		primaryStage.setOnShown( new EventHandler< WindowEvent >()
		{
			@Override public void handle( WindowEvent event )
			{
				if( new File(getUserDataDirectory() + "layout.pref").exists() )
					dockPane.loadPreference( getUserDataDirectory() + "layout.pref" );
			}
		} );

		primaryStage.setOnCloseRequest(new EventHandler<WindowEvent >()
		{
			@Override
			public void handle(WindowEvent event)
			{
				dockPane.storePreference( getUserDataDirectory() + "layout.pref" );
			}
		});

	public static String getUserDataDirectory() {
		return System.getProperty("user.home") + File.separator + ".yourProject" + File.separator + getApplicationVersionString() + File.separator;
	}

	public static String getApplicationVersionString() {
		return "1.0";
	}
```

In the above case, I do not see any errors for storing/restoring. Could you check it?


> Are you using this library at work ?
Yes!

Thank you for your contribution! I will accept your PR as soon as possible.

Cheers,
HongKee

**Comment by MilWolf** [comment]
> In the above case, I do not see any errors for storing/restoring. Could you check it?

But you need to dock all nodes before loading preferences, right ? Otherwise we get "dock node is not present"

A system to load preferences after closing some nodes but without closing application would be great.
Typically having a set of preferences for the application that the user can load to organize docknode inside the dockpane.

You are showing an example where the DockNode are docked then preferences are loaded, but this surely works.

> I will accept your PR as soon as possible.

Do you need any help for this or my code is clean enough?

Cheers,

MilWolf.

**Pull request closed without merging**
