### PR TITLE
Add minimize functionality and fix of a bug of view

### PR DESCRIPTION
**Pull request by MilWolf**
-Add minimize functionality
    ->minimize only works when the DockNode is floating
    ->minimize calls iconify function

-Fix a bug causing the docknode to disappear (Linux Mint 64 bits, java 8 Oracle)
    ->appears when the user drag a docknode outside, then maximize the floating node and maximize again the floating node

### CODE REVIEW

**Comment by SamCooper** [comment]
Did you reformat the code in your commits? Its really difficult to see what you've changed as a result.

Would it be possible for you to reapply the changes to a fresh clone so that we can see the actual changes?

**Comment by MilWolf** [comment]
Hello,

I will be working on this next week.

Cheers,

MilWolf.

2016-10-26 14:09 GMT+02:00 Sam Cooper <notifications@github.com>:

**Comment by MilWolf** [comment]
I submit a new pull request.

**Comment by hkmoon** [comment]
Close it by using the latest one

**Pull request closed without merging**
