### PR TITLE
Add minimize functionality and fix of a bug of view - reimplemented without formatting code

### PR DESCRIPTION
**Pull request by MilWolf**
-Add minimize functionality
-Fix of a bug of view : floating pane disappear sometimes

### CODE REVIEW

**Comment by hkmoon** [comment]
@MilWolf 
Thank you for the PR!! Does this mean that I can ignore the previous PR and check this instead?

**Comment by MilWolf** [comment]
Exactly ! Thanks to you.

**Comment by hkmoon** [comment]
Hi @MilWolf 
When I terminate the program while some DockNode is minimized, the application is still running.
Could you make it finished when the application exits?

**Comment by MilWolf** [comment]
I did the changes to close floating nodes when the owner stage is closed but this led to a confilct with the file DockNode.java.

**Comment by hkmoon** [comment]
I figured it out. You can check it the head of master now.

**Pull request closed without merging**
