### PR TITLE
Multi dock support

### PR DESCRIPTION
**Pull request by SamCooper**
This is a fairly massive change that does (approximately) the following:

Reformatting of the code to a single consistent style matching that of JFX (see #15)
Refactoring the DockNode/DockPane code so that most docking code is in DockPane (see #16)
Implemented the ability to Dock floating nodes into other floating nodes (see #17)

The basic approach for the multi-docking support is that DockNode now cannot exist outside a DockPane, so when you float a node it creates a new DockPane for it to float in.

### CODE REVIEW

**Comment by hkmoon** [comment]
Hi, @SamCooper 

After your new commits, I cannot compile it because there are some differences including `DockEvent`'s signature is changed.
Could you have a look? My plan is to merge your PR and make hkmoon branch up-to-date for another PR in my repo.

**Comment by hkmoon** [comment]
Hi @SamCooper 

Could you check why the conflicts appeared? I saw it was able to be merged before you new commits.

**Comment by SamCooper** [comment]
Hi @hkmoon 

I'm not sure that it was the latest changes that broke anything, I suspect GitHub was being misleading.

**Comment by hkmoon** [comment]
@SamCooper You are right! I noticed that github stopped before in the previous Friday.

**Comment by SamCooper** [comment]
Wow, did you manage to merge that? That was a very big change

**Comment by hkmoon** [comment]
Now, I am stuck on ```ContentTabPaneSkin```. ;) Should be fixed soon and I'd like to test it.

**Comment by SamCooper** [comment]
Is there some way I can "clone" this change request work to help/check from my side?

**Comment by hkmoon** [comment]
Actually, your branch is now up-to-date with my changes. 
```
(in your repo)
git checkout Multi-dock
git pull
```
You can see my changes. Hopefully, I did not break your precious codes!

**Comment by SamCooper** [comment]
I didn't even know you'd be able to do that!

I am worried that the exclusive and minimise changes made in your master branch have not been merged as there doesn't seem to be any changes other than mine?

**Comment by hkmoon** [comment]
Yes, you're right. Even I didn't know I could update your source codes. Actually, I intended to update my repo and check if all the sources codes working together including exclusive mode and minimize.
Hmm.. I need to dig in more..
Thank you for your help. I will keep you updated.

**Comment by SamCooper** [comment]
To help you, the logical changes are that DockNodes are just nodes now, DockPanes are the containers.
All mouse/event handling has been moved into the title bar classes,

**Comment by hkmoon** [comment]
I think I need to roll back the change which I made in ClearControl/DockFX.

**Comment by SamCooper** [comment]
@hkmoon I've had a go at the merge:

https://github.com/SamCooper/DockFX/tree/MultiDockMerge

Seems to work from my limited 5 minute test but I've probably broken many things. But probably the best starting point to continue from if you'd like to take it.

**Comment by hkmoon** [comment]
@SamCooper Thank you so much!

However, I noticed that some strange things when I ran ```org.dockfx.demo.DockFX```.

1.  when I detached a window form dockPane, it lost dragging status, resized and situated center of the main window. (was it intentional?)
2. when I dock the undocked node in the left of "Tabs Dock" again and tried to detach it, it gave the error like below:

```java
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at org.dockfx.DockNodeTitleBar.handle(DockNodeTitleBar.java:175)
	at org.dockfx.DockNodeTitleBar.handle(DockNodeTitleBar.java:37)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
```

What did I do wrong? Thanks again!

**Comment by SamCooper** [comment]
@hkmoon 

1) No, but that is far as I got replicating the original behaviour. The problem is that the new floating dockpane uses a different title bar from the docked docknode.

2) I see that also now that I have tried, I can see the problem and am working on a fix now.


I think there will be a few problems created by the merge but hopefully they should be fixable.

**Comment by hkmoon** [comment]
> No, but that is far as I got replicating the original behaviour. The problem is that the new floating dockpane uses a different title bar from the docked docknode.

Yup, I corrected some codes after merging the previous PR because of it.
I should have a look on `org/dockfx/DockPane.java:585` in master with your code.
Thanks!

**Comment by SamCooper** [comment]
I should say that the merge update you did on my original branch should be ignored because it actually overwrote most of the changes made by other contributors.

I think the more recent merge I did should be the baseline going forwards, so any change you made after the original merge should be reapplied.

**Comment by SamCooper** [comment]
@hkmoon would it be possible for you to email me (in profile) as I think it'll be quicker than via GitHub.

**Pull request merged**
